"""
1.2PP Hello World
"""

__author__ = "Samuel Morriss"

def main(): # It's The Bee Movie script!
    print("According to all known laws of aviation, there is no way a bee should be able to fly.")
    print("Its wings are too small to get its fat little body off the ground.")
    print("The bee, of course, flies anyway because bees don't care what humans think is impossible.")
    print("Yellow, black. Yellow, black. Yellow, black. Yellow, black.")
    print("Ooh, black and yellow!")
    print("Let's shake it up a little.")
    print("Barry! Breakfast is ready!")
    print("Coming!")
    print("Hang on a second.")
    print("Hello?")
    print("Barry?")
    print("Adam?")
    print("Can you believe this is happening?")
    print("I can't.")
    print("I'll pick you up.")
    print("Looking sharp.")
    print("Use the stairs, Your father paid good money for those.")
    print("Sorry. I'm excited.")
    print("Here's the graduate.")
    print("We're very proud of you, son.")
    print("A perfect report card, all B's.")
    print("Very proud.")
    print("Ma! I got a thing going here.")
    print("You got lint on your fuzz.")
    print("Ow! That's me!")
    print("Wave to us! We'll be in row 118,000.")
    print("Bye!")
    print("Barry, I told you, stop flying in the house!")
    print("Hey, Adam.")
    print("Hey, Barry.")
    print("Is that fuzz gel?")
    print("A little. Special day, graduation.")
    print("Never thought I'd make it.")
    print("Three days grade school, three days high school.")
    print("Those were awkward.")
    print("Three days college. I'm glad I took a day and hitchhiked around The Hive.")
    print("You did come back different.")
    print("Hi, Barry. Artie, growing a mustache? Looks good.")
    print("Hear about Frankie?")
    print("Yeah.")
    print("You going to the funeral?")
    print("No, I'm not going.")
    print("Everybody knows, sting someone, you die.")
    print("Don't waste it on a squirrel.")
    print("Such a hothead.")
    print("I guess he could have just gotten out of the way.")
    print("I love this incorporating an amusement park into our day.")
    print("That's why we don't need vacations.")
    print("Boy, quite a bit of pomp under the circumstances.")
    print("Well, Adam, today we are men.")
    print("We are!")
    print("Bee-men.")
    print("Amen!")
    print("Hallelujah!")
    print("Students, faculty, distinguished bees,")
    print("please welcome Dean Buzzwell.")
    print("Welcome, New Hive City graduating class of 9:15.")
    print("That concludes our ceremonies And begins your career at Honex Industries!")
    print("Will we pick our job today?")
    print("I heard it's just orientation.")
    print("Heads up! Here we go.")
    print("Keep your hands and antennas inside the tram at all times.")
    print("Wonder what it'll be like?")
    print("A little scary.")
    print("Welcome to Honex, a division of Honesco and a part of the Hexagon Group.")
    print("This is it!")
    print("Wow.")
    print("Wow.")
    print("We know that you, as a bee, have worked your whole life to get to the point where you can work for your whole life.")
    print("Honey begins when our valiant Pollen Jocks bring the nectar to The Hive.")
    print("Our top-secret formula is automatically color-corrected, scent-adjusted and bubble-contoured into this soothing sweet syrup with its distinctive golden glow you know as... Honey!")
    print("That girl was hot.")
    print("She's my cousin!")
    print("She is?")
    print("Yes, we're all cousins.")
    print("Right. You're right.")
    print("At Honex, we constantly strive to improve every aspect of bee existence.")
    print("These bees are stress-testing a new helmet technology.")
    print("What do you think he makes?")
    print("Not enough.")
    print("Here we have our latest advancement, the Krelman.")
    print("What does that do?")
    print("Catches that little strand of honey that hangs after you pour it.")
    print("Saves us millions.")
    print("Can anyone work on the Krelman?")
    print("Of course. Most bee jobs are small ones.")
    print("But bees know that every small job, if it's done well, means a lot.")
    print("But choose carefully because you'll stay in the job you pick for the rest of your life.")
    print("The same job the rest of your life? I didn't know that.")
    print("What's the difference?")
    print("You'll be happy to know that bees, as a species, haven't had one day off in 27 million years.")
    print("So you'll just work us to death?")
    print("We'll sure try.")
    print("Wow! That blew my mind!")
    print('"What'+"'s the"+' difference?"')
    print("How can you say that?")
    print("One job forever?")
    print("That's an insane choice to have to make.")
    print("I'm relieved. Now we only have to make one decision in life.")
    print("But, Adam, how could they never have told us that?")
    print("Why would you question anything? We're bees.")
    print("We're the most perfectly functioning society on Earth.")
    print("You ever think maybe things work a little too well here?")
    print("Like what? Give me one example.")
    print("I don't know. But you know what I'm talking about.")
    print("Please clear the gate. Royal Nectar Force on approach.")
    print("Wait a second. Check it out.")
    print("Hey, those are Pollen Jocks!")
    print("Wow.")
    print("I've never seen them this close.")
    print("They know what it's like outside The Hive.")
    print("Yeah, but some don't come back.")
    print("Hey, Jocks!")
    print("Hi, Jocks!")
    print("You guys did great!")
    print("You're monsters!")
    print("You're sky freaks! I love it! I love it!")
    print("I wonder where they were.")
    print("I don't know.")
    print("Their day's not planned.")
    print("Outside The Hive, flying who knows where, doing who knows what.")
    print("You can't just decide to be a Pollen Jock. You have to be bred for that.")
    print("Right.")
    print("Look. That's more pollen than you and I will see in a lifetime.")
    print("It's just a status symbol.")
    print("Bees make too much of it.")
    print("Perhaps. Unless you're wearing it and the ladies see you wearing it.")
    print("Those ladies?")
    print("Aren't they our cousins too?")
    print("Distant. Distant.")
    print("Look at these two.")
    print("Couple of Hive Harrys.")
    print("Let's have fun with them.")
    print("It must be dangerous being a Pollen Jock.")
    print("Yeah. Once a bear pinned me against a mushroom!")
    print("He had a paw on my throat, and with the other, he was slapping me!")
    print("Oh, my!")
    print("I never thought I'd knock him out.")
    print("What were you doing during this?")
    print("Trying to alert the authorities.")
    print("I can autograph that.")
    print("A little gusty out there today, wasn't it, comrades?")
    print("Yeah. Gusty.")
    print("We're hitting a sunflower patch six miles from here tomorrow.")
    print("Six miles, huh?")
    print("Barry!")
    print("A puddle jump for us, but maybe you're not up for it.")
    print("Maybe I am.")
    print("You are not!")
    print("We're going 0900 at J-Gate.")
    print("What do you think, buzzy-boy?")
    print("Are you bee enough?")
    print("I might be. It all depends on what 0900 means.")
    print("Hey, Honex!")
    print("Dad, you surprised me.")
    print("You decide what you're interested in?")
    print("Well, there's a lot of choices.")
    print("But you only get one.")
    print("Do you ever get bored doing the same job every day?")
    print("Son, let me tell you about stirring.")
    print("You grab that stick, and you just move it around, and you stir it around.")
    print("You get yourself into a rhythm.")
    print("It's a beautiful thing.")
    print("You know, Dad, the more I think about it,")
    print("maybe the honey field just isn't right for me.")
    print("You were thinking of what, making balloon animals?")
    print("That's a bad job for a guy with a stinger.")
    print("Janet, your son's not sure he wants to go into honey!")
    print("Barry, you are so funny sometimes.")
    print("I'm not trying to be funny.")
    print("You're not funny! You're going into honey. Our son, the stirrer!")
    print("You're gonna be a stirrer?")
    print("No one's listening to me!")
    print("Wait till you see the sticks I have.")
    print("I could say anything right now.")
    print("I'm gonna get an ant tattoo!")
    print("Let's open some honey and celebrate!")
    print("Maybe I'll pierce my thorax. Shave my antennae. Shack up with a grasshopper. Get a gold tooth and call everybody"+' "dawg"!')
    print("I'm so proud.")
    print("We're starting work today!")
    print("Today's the day.")
    print("Come on! All the good jobs will be gone.")
    print("Yeah, right.")
    print("Pollen counting, stunt bee, pouring, stirrer, front desk, hair removal...")
    print("Is it still available?")
    print("Hang on. Two left!")
    print("One of them's yours! Congratulations!")
    print("Step to the side.")
    print("What'd you get?")
    print("Picking crud out. Stellar!")
    print("Wow!")
    print("Couple of newbies?")
    print("Yes, sir! Our first day! We are ready!")
    print("Make your choice.")
    print("You want to go first?")
    print("No, you go.")
    print("Oh, my. What's available?")
    print("Restroom attendant's open, not for the reason you think.")
    print("Any chance of getting the Krelman?")
    print("Sure, you're on.")
    print("I'm sorry, the Krelman just closed out.")
    print("Wax monkey's always open.")
    print("The Krelman opened up again.")
    print("What happened?")
    print("A bee died. Makes an opening. See? He's dead. Another dead one.")
    print("Deady. Deadified. Two more dead.")
    print("Dead from the neck up. Dead from the neck down. That's life!")
    print("Oh, this is so hard!")
    print("Heating, cooling, stunt bee, pourer, stirrer, humming, inspector number seven, lint coordinator, stripe supervisor, mite wrangler.")
    print("Barry, what do you think I should... Barry?")
    print("Barry!")
    print("All right, we've got the sunflower patch in quadrant nine...")
    print("What happened to you?")
    print("Where are you?")
    print("I'm going out.")
    print("Out? Out where?")
    print("Out there.")
    print("Oh, no!")
    print("I have to, before I go to work for the rest of my life.")
    print("You're gonna die! You're crazy! Hello?")
    print("Another call coming in.")
    print("If anyone's feeling brave, there's a Korean deli on 83rd that gets their roses today.")
    print("Hey, guys.")
    print("Look at that.")
    print("Isn't that the kid we saw yesterday?")
    print("Hold it, son, flight deck's restricted.")
    print("It's OK, Lou. We're gonna take him up.")
    print("Really? Feeling lucky, are you?")
    print("Sign here, here. Just initial that.")
    print("Thank you.")
    print("OK.")
    print("You got a rain advisory today, and as you all know, bees cannot fly in rain.")
    print("So be careful. As always, watch your brooms, hockey sticks, dogs, birds, bears and bats.")
    print("Also, I got a couple of reports of root beer being poured on us.")
    print("Murphy's in a home because of it, babbling like a cicada!")
    print("That's awful.")
    print("And a reminder for you rookies, bee law number one, absolutely no talking to humans!")
    print(" All right, launch positions!")
    print("Buzz, buzz, buzz, buzz! Buzz, buzz, buzz, buzz! Buzz, buzz, buzz, buzz!")
    print("Black and yellow!")
    print("Hello!")
    print("You ready for this, hot shot?")
    print("Yeah. Yeah, bring it on.")
    print("Wind, check.")
    print("Antennae, check.")
    print("Nectar pack, check.")
    print("Wings, check.")
    print("Stinger, check.")
    print("Scared out of my shorts, check.")
    print("OK, ladies,")
    print("let's move it out!")
    print("Pound those petunias, you striped stem-suckers!")
    print("All of you, drain those flowers!")
    print("Wow! I'm out!")
    print("I can't believe I'm out!")
    print("So blue.")
    print("I feel so fast and free!")
    print("Box kite!")
    print("Wow!")
    print("Flowers!")
    print("This is Blue Leader, We have roses visual.")
    print("Bring it around 30 degrees and hold.")
    print("Roses!")
    print("30 degrees, roger. Bringing it around.")
    print("Stand to the side, kid.")
    print("It's got a bit of a kick.")
    print("That is one nectar collector!")
    print("Ever see pollination up close?")
    print("No, sir.")
    print("I pick up some pollen here, sprinkle it over here. Maybe a dash over there, a pinch on that one.")
    print("See that? It's a little bit of magic.")
    print("That's amazing. Why do we do that?")
    print("That's pollen power. More pollen, more flowers, more nectar, more honey for us.")
    print("Cool.")
    print("I'm picking up a lot of bright yellow, Could be daisies, Don't we need those?")
    print("Copy that visual.")
    print("Wait. One of these flowers seems to be on the move.")
    print("Say again? You're reporting a moving flower?")
    print("Affirmative.")
    print("That was on the line!")
    print("This is the coolest. What is it?")
    print("I don't know, but I'm loving this color.")
    print("It smells good.")
    print("Not like a flower, but I like it.")
    print("Yeah, fuzzy.")
    print("Chemical-y.")
    print("Careful, guys. It's a little grabby.")
    print("My sweet lord of bees!")
    print("Candy-brain, get off there!")
    print("Problem!")
    print("Guys!")
    print("This could be bad.")
    print("Affirmative.")
    print("Very close.")
    print("Gonna hurt.")
    print("Mama's little boy.")
    print("You are way out of position, rookie!")
    print("Coming in at you like a missile!")
    print("Help me!")
    print("I don't think these are flowers.")
    print("Should we tell him?")
    print("I think he knows.")
    print("What is this?!")
    print("Match point!")
    print("You can start packing up, honey, because you're about to eat it!")
    print("Yowser!")
    print("Gross.")
    print("There's a bee in the car!")
    print("Do something!")
    print("I'm driving!")
    print("Hi, bee.")
    print("He's back here!")
    print("He's going to sting me!")
    print("Nobody move. If you don't move, he won't sting you. Freeze!")
    print("He blinked!")
    print("Spray him, Granny!")
    print("What are you doing?!")
    print("Wow... the tension level out here is unbelievable.")
    print("I gotta get home.")
    print("Can't fly in rain. Can't fly in rain. Can't fly in rain.")
    print("Mayday! Mayday! Bee going down!")
    print("Ken, could you close the window please?")
    print("Ken, could you close the window please?")
    print("Check out my new resume. I made it into a fold-out brochure. You see? Folds out.")
    print("Oh, no. More humans. I don't need this.")
    print("What was that?")
    print("Maybe this time. This time. This time. This time! This time! This... Drapes!")
    print("That is diabolical.")
    print("It's fantastic. It's got all my special skills, even my top-ten favorite movies.")
    print("What's number one? Star Wars?")
    print("Nah, I don't go for that... kind of stuff.")
    print("No wonder we shouldn't talk to them. They're out of their minds.")
    print("When I leave a job interview, they're flabbergasted, can't believe what I say.")
    print("There's the sun. Maybe that's a way out.")
    print("I don't remember the sun having a big 75 on it.")
    print("I predicted global warming. I could feel it getting hotter. At first I thought it was just me.")
    print("Wait! Stop! Bee!")
    print("Stand back. These are winter boots.")
    print("Wait!")
    print("Don't kill him!")
    print("You know I'm allergic to them! This thing could kill me!")
    print("Why does his life have less value than yours?")
    print("Why does his life have any less value than mine? Is that your statement?")
    print("I'm just saying all life has value. You don't know what he's capable of feeling.")
    print("My brochure!")
    print("There you go, little guy.")
    print("I'm not scared of him.It's an allergic thing.")
    print(" Put that on your resume brochure.")
    print("My whole face could puff up.")
    print("Make it one of your special skills.")
    print("Knocking someone out is also a special skill.")
    print("Right. Bye, Vanessa. Thanks.")
    print("Vanessa, next week? Yogurt night?")
    print("Sure, Ken. You know, whatever.")
    print("You could put carob chips on there.")
    print("Bye.")
    print("Supposed to be less calories.")
    print("Bye.")
    print("I gotta say something. She saved my life. I gotta say something.")
    print("All right, here it goes.")
    print("Nah.")
    print("What would I say?")
    print("I could really get in trouble. It's a bee law. You're not supposed to talk to a human.")
    print("I can't believe I'm doing this. I've got to.")
    print("Oh, I can't do it. Come on!")
    print("No. Yes. No. Do it. I can't.")
    print('How should I start it? "You like jazz?"'+" No, that's no good.")
    print("Here she comes! Speak, you fool!")
    print("Hi!")
    print("I'm sorry. You're talking.")
    print("Yes, I know.")
    print("You're talking!")
    print("I'm so sorry.")
    print("No, it's OK. It's fine.")
    print("I know I'm dreaming. But I don't recall going to bed.")
    print("Well, I'm sure this is very disconcerting.")
    print("This is a bit of a surprise to me. I mean, you're a bee!")
    print("I am. And I'm not supposed to be doing this, but they were all trying to kill me.")
    print("And if it wasn't for you... I had to thank you. It's just how I was raised.")
    print("That was a little weird. I'm talking with a bee.")
    print("Yeah.")
    print("I'm talking to a bee. And the bee is talking to me!")
    print("I just want to say I'm grateful.")
    print("I'll leave now.")
    print("Wait! How did you learn to do that?")
    print("What?")
    print("The talking thing.")
    print('Same way you did, I guess. "Mama, Dada, honey." You pick it up.')
    print("That's very funny.")
    print("Yeah.")
    print("Bees are funny. If we didn't laugh, we'd cry with what we have to deal with.")
    print("Anyway... Can I... get you something?")
    print("Like what?")
    print("I don't know. I mean... I don't know. Coffee?")
    print("I don't want to put you out.")
    print("It's no trouble. It takes two minutes.")
    print("It's just coffee.")
    print("I hate to impose.")
    print("Don't be ridiculous!")
    print("Actually, I would love a cup.")
    print("Hey, you want rum cake?")
    print("I shouldn't.")
    print("Have some.")
    print("No, I can't.")
    print("Come on!")
    print("I'm trying to lose a couple micrograms.")
    print("Where?")
    print("These stripes don't help.")
    print("You look great!")
    print("I don't know if you know anything about fashion.")
    print("Are you all right?")
    print("No.")
    print("He's making the tie in the cab as they're flying up Madison.")
    print("He finally gets there.")
    print("He runs up the steps into the church.")
    print("The wedding is on.")
    print('And he says, "Watermelon?')
    print("I thought you said Guatemalan.")
    print('Why would I marry a watermelon?"')
    print("Is that a bee joke?")
    print("That's the kind of stuff we do.")
    print("Yeah, different.")
    print("So, what are you gonna do, Barry?")
    print("About work? I don't know.")
    print("I want to do my part for The Hive, but I can't do it the way they want.")
    print("I know how you feel.")
    print("You do?")
    print("Sure.")
    print("My parents wanted me to be a lawyer or a doctor, but I wanted to be a florist.")
    print("Really?")
    print("My only interest is flowers.")
    print("Our new queen was just elected with that same campaign slogan.")
    print("Anyway, if you look... There's my hive right there. See it?")
    print("You're in Sheep Meadow!")
    print("Yes! I'm right off the Turtle Pond!")
    print("No way! I know that area. I lost a toe ring there once.")
    print("Why do girls put rings on their toes?")
    print("Why not?")
    print("It's like putting a hat on your knee.")
    print("Maybe I'll try that.")
    print("You all right, ma'am?")
    print("Oh, yeah. Fine.")
    print("Just having two cups of coffee!")
    print("Anyway, this has been great.")
    print("Thanks for the coffee.")
    print("Yeah, it's no trouble.")
    print("Sorry I couldn't finish it. If I did, I'd be up the rest of my life.")
    print("Are you...?")
    print("Can I take a piece of this with me?")
    print("Sure! Here, have a crumb.")
    print("Thanks!")
    print("Yeah.")
    print("All right. Well, then... I guess I'll see you around. Or not.")
    print("OK, Barry.")
    print("And thank you so much again... for before.")
    print("Oh, that? That was nothing.")
    print("Well, not nothing, but... Anyway...")
    print("This can't possibly work.")
    print("He's all set to go.")
    print("We may as well try it.")
    print("OK, Dave, pull the chute.")
    print("Sounds amazing.")
    print("It was amazing!")
    print("It was the scariest, happiest moment of my life.")
    print("Humans! I can't believe you were with humans!")
    print("Giant, scary humans!")
    print("What were they like?")
    print("Huge and crazy. They talk crazy.")
    print("They eat crazy giant things.")
    print("They drive crazy.")
    print("Do they try and kill you, like on TV?")
    print("Some of them. But some of them don't.")
    print("How'd you get back?")
    print("Poodle.")
    print("You did it, and I'm glad. You saw whatever you wanted to see.")
    print('You had your "experience." Now you can pick out yourjob and be normal.')
    print("Well...")
    print("Well?")
    print("Well, I met someone.")
    print("You did? Was she Bee-ish?")
    print("A wasp?! Your parents will kill you!")
    print("No, no, no, not a wasp.")
    print("Spider?")
    print("I'm not attracted to spiders.")
    print("I know it's the hottest thing, with the eight legs and all. I can't get by that face.")
    print("So who is she?")
    print("She's... human.")
    print("No, no. That's a bee law. You wouldn't break a bee law.")
    print("Her name's Vanessa.")
    print("Oh, boy.")
    print("She's so nice. And she's a florist!")
    print("Oh, no! You're dating a human florist!")
    print("We're not dating.")
    print("You're flying outside The Hive, talking to humans that attack our homes with power washers and M-80s! One-eighth a stick of dynamite!")
    print("She saved my life! And she understands me.")
    print("This is over!")
    print("Eat this.")
    print("This is not over! What was that?")
    print("They call it a crumb.")
    print("It was so stingin' stripey!")
    print("And that's not what they eat.")
    print("That's what falls off what they eat!")
    print("You know what a Cinnabon is?")
    print("No.")
    print("It's bread and cinnamon and frosting. They heat it up...")
    print("Sit down!")
    print("...really hot!")
    print("Listen to me!")
    print("We are not them! We're us.")
    print("There's us and there's them!")
    print("Yes, but who can deny the heart that is yearning?")
    print("There's no yearning. Stop yearning. Listen to me!")
    print("You have got to start thinking bee, my friend. Thinking bee!")
    print("Thinking bee.")
    print("Thinking bee.")
    print("Thinking bee! Thinking bee! Thinking bee! Thinking bee!")
    print("There he is. He's in the pool.")
    print("You know what your problem is, Barry?")
    print("I gotta start thinking bee?")
    print("How much longer will this go on?")
    print("It's been three days! Why aren't you working?")
    print("I've got a lot of big life decisions to think about.")
    print("What life? You have no life!")
    print("You have no job. You're barely a bee!")
    print("Would it kill you to make a little honey?")
    print("Barry, come out. Your father's talking to you.")
    print("Martin, would you talk to him?")
    print("Barry, I'm talking to you!")
    print("You coming?")
    print("Got everything?")
    print("All set!")
    print("Go ahead. I'll catch up.")
    print("Don't be too long.")
    print("Watch this!")
    print("Vanessa!")
    print("We're still here.")
    print("I told you not to yell at him.")
    print("He doesn't respond to yelling!")
    print("Then why yell at me?")
    print("Because you don't listen!")
    print("I'm not listening to this.")
    print("Sorry, I've gotta go.")
    print("Where are you going?")
    print("I'm meeting a friend.")
    print("A girl? Is this why you can't decide?")
    print("Bye.")
    print("I just hope she's Bee-ish.")
    print("They have a huge parade of flowers every year in Pasadena?")
    print("To be in the Tournament of Roses, that's every florist's dream!")
    print("Up on a float, surrounded by flowers, crowds cheering.")
    print("A tournament. Do the roses compete in athletic events?")
    print("No. All right, I've got one.")
    print("How come you don't fly everywhere?")
    print("It's exhausting. Why don't you run everywhere? It's faster.")
    print("Yeah, OK, I see, I see.")
    print("All right, your turn.")
    print("TiVo. You can just freeze live TV? That's insane!")
    print("You don't have that?")
    print("We have Hivo, but it's a disease. It's a horrible, horrible disease.")
    print("Oh, my.")
    print("Dumb bees!")
    print("You must want to sting all those jerks.")
    print("We try not to sting. It's usually fatal for us.")
    print("So you have to watch your temper.")
    print("Very carefully.")
    print("You kick a wall, take a walk, write an angry letter and throw it out. Work through it like any emotion: Anger, jealousy, lust.")
    print("Oh, my goodness! Are you OK?")
    print("Yeah.")
    print("What is wrong with you?!")
    print("It's a bug.")
    print("He's not bothering anybody.")
    print("Get out of here, you creep!")
    print("What was that? A Pic 'N' Save circular?")
    print("Yeah, it was. How did you know?")
    print("It felt like about 10 pages. Seventy-five is pretty much our limit.")
    print("You've really got that down to a science.")
    print("I lost a cousin to Italian Vogue.")
    print("I'll bet.")
    print("What in the name of Mighty Hercules is this?")
    print("How did this get here? cute Bee, Golden Blossom, Ray Liotta Private Select?")
    print("Is he that actor?")
    print("I never heard of him.")
    print("Why is this here?")
    print("For people. We eat it.")
    print("You don't have enough food of your own?")
    print("Well, yes.")
    print("How do you get it?")
    print("Bees make it.")
    print("I know who makes it! And it's hard to make it!")
    print("There's heating, cooling, stirring. You need a whole Krelman thing!")
    print("It's organic.")
    print("It's our-ganic!")
    print("It's just honey, Barry.")
    print("Just what?!")
    print("Bees don't know about this! This is stealing! A lot of stealing!")
    print("You've taken our homes, schools,hospitals! This is all we have!")
    print("And it's on sale?! I'm getting to the bottom of this.")
    print("I'm getting to the bottom of all of this!")
    print("Hey, Hector. You almost done?")
    print("Almost.")
    print("He is here. I sense it.")
    print("Well, I guess I'll go home now and just leave this nice honey out, with no one around.")
    print("You're busted, box boy!")
    print("I knew I heard something.")
    print("So you can talk!")
    print("I can talk. And now you'll start talking!")
    print("Where you getting the sweet stuff? Who's your supplier?")
    print("I don't understand.")
    print("I thought we were friends.")
    print("The last thing we want to do is upset bees!")
    print("You're too late! It's ours now!")
    print("You, sir, have crossed the wrong sword!")
    print("You, sir, will be lunch for my iguana, Ignacio!")
    print("Where is the honey coming from? Tell me where!")
    print("Honey Farms! It comes from Honey Farms!")
    print("Crazy person!")
    print("What horrible thing has happened here?")
    print("These faces, they never knew what hit them. And now")
    print("they're on the road to nowhere!")
    print("Just keep still.")
    print("What? You're not dead?")
    print("Do I look dead? They will wipe anything that moves. Where you headed?")
    print("To Honey Farms. I am onto something huge here.")
    print("I'm going to Alaska. Moose blood, crazy stuff. Blows your head off!")
    print("I'm going to Tacoma.")
    print("And you?")
    print("He really is dead.")
    print("All right.")
    print("Uh-oh!")
    print("What is that?!")
    print("Oh, no!")
    print("A wiper! Triple blade!")
    print("Triple blade?")
    print("Jump on! It's your only chance, bee!")
    print("Why does everything have")
    print("to be so doggone clean?!")
    print("How much do you people need to see?!")
    print("Open your eyes!")
    print("Stick your head out the window!")
    print("From NPR News in Washington,")
    print("I'm Carl Kasell.")
    print("But don't kill no more bugs!")
    print("Bee!")
    print("Moose blood guy!!")
    print("You hear something?")
    print("Like what?")
    print("Like tiny screaming.")
    print("Turn off the radio.")
    print("Whassup, bee boy?")
    print("Hey, Blood.")
    print("Just a row of honey jars, as far as the eye could see.")
    print("Wow!")
    print("I assume wherever this truck goes is where they're getting it. I mean, that honey's ours.")
    print("Bees hang tight. We're all jammed in.")
    print("It's a close community.")
    print("Not us, man. We on our own. Every mosquito on his own.")
    print("What if you get in trouble?")
    print("You a mosquito, you in trouble. Nobody likes us. They just smack. See a mosquito, smack, smack!")
    print("At least you're out in the world. You must meet girls.")
    print("Mosquito girls try to trade up, get with a moth, dragonfly. Mosquito girl don't want no mosquito.")
    print("You got to be kidding me!")
    print("Mooseblood's about to leave the building! So long, bee!")
    print("Hey, guys!")
    print("Mooseblood!")
    print("I knew I'd catch y'all down here.")
    print("Did you bring your crazy straw?")
    print("We throw it in jars, slap a label on it, and it's pretty much pure profit.")
    print("What is this place?")
    print("A bee's got a brain the size of a pinhead.")
    print("They are pinheads!")
    print("Pinhead.")
    print("Check out the new smoker.")
    print("Oh, sweet. That's the one you want. The Thomas 3000!")
    print("Smoker?")
    print("Ninety puffs a minute, semi-automatic. Twice the nicotine, all the tar. A couple breaths of this knocks them right out.")
    print("They make the honey, and we make the money.")
    print('"They make the honey, and we make the money"?')
    print("Oh, my!")
    print("What's going on? Are you OK?")
    print("Yeah. It doesn't last too long.")
    print("Do you know you're in a fake hive with fake walls?")
    print("Our queen was moved here. We had no choice.")
    print("This is your queen? That's a man in women's clothes! That's a drag queen!")
    print("What is this?")
    print("Oh, no!")
    print("There's hundreds of them!")
    print("Bee honey.")
    print("Our honey is being brazenly stolen on a massive scale!")
    print("This is worse than anything bears have done! I intend to do something.")
    print("Oh, Barry, stop.")
    print("Who told you humans are taking our honey? That's a rumor.")
    print("Do these look like rumors?")
    print("That's a conspiracy theory. These are obviously doctored photos. How did you get mixed up in this?")
    print("He's been talking to humans.")
    print("What? Talking to humans?!")
    print("He has a human girlfriend. And they make out!")
    print("Make out? Barry!")
    print("We do not.")
    print("You wish you could.")
    print("Whose side are you on?")
    print("The bees!")
    print("I dated a cricket once in San Antonio. Those crazy legs kept me up all night.")
    print("Barry, this is what you want to do with your life?")
    print("I want to do it for all our lives. Nobody works harder than bees!")
    print("Dad, I remember you coming home so overworked")
    print("your hands were still stirring. You couldn't stop.")
    print("I remember that.")
    print("What right do they have to our honey?")
    print("We live on two cups a year. They put it in lip balm for no reason whatsoever!")
    print("Even if it's true, what can one bee do?")
    print("Sting them where it really hurts.")
    print("In the face! The eye!")
    print("That would hurt.")
    print("No.")
    print("Up the nose? That's a killer.")
    print("There's only one place you can sting the humans, one place where it matters.")
    print("Hive at Five, The Hive's only full-hour action news source.")
    print("No more bee beards!")
    print("With Bob Bumble at the anchor desk. Weather with Storm Stinger. Sports with Buzz Larvi. And Jeanette Chung.")
    print("Good evening. I'm Bob Bumble.")
    print("And I'm Jeanette Ohung.")
    print("A tri-county bee, Barry Benson, intends to sue the human race for stealing our honey, packaging it and profiting from it illegally!")
    print("Tomorrow night on Bee Larry King, we'll have three former queens here in our studio, discussing their new book, classy Ladies, out this week on Hexagon.")
    print("Tonight we're talking to Barry Benson.")
    print("Did you ever think, "+'"I'+"'m"+' a kid from The Hive. I can'+"'"+'t do this"?')
    print("Bees have never been afraid to change the world.")
    print("What about Bee Oolumbus? Bee Gandhi? Bejesus?")
    print("Where I'm from, we'd never sue humans.")
    print("We were thinking of stickball or candy stores.")
    print("How old are you?")
    print("The bee community is supporting you in this case, which will be the trial of the bee century.")
    print("You know, they have a Larry King in the human world too.")
    print("It's a common name. Next week...")
    print("He looks like you and has a show and suspenders and colored dots...")
    print("Next week...")
    print("Glasses, quotes on the bottom from the guest even though you just heard 'em.")
    print("Bear Week next week! They're scary, hairy and here live.")
    print("Always leans forward, pointy shoulders, squinty eyes, very Jewish.")
    print("In tennis, you attack at the point of weakness!")
    print("It was my grandmother, Ken. She's 81.")
    print("Honey, her backhand's a joke!")
    print("I'm not gonna take advantage of that?")
    print("Quiet, please.")
    print("Actual work going on here.")
    print("Is that that same bee?")
    print("Yes, it is!")
    print("I'm helping him sue the human race.")
    print("Hello.")
    print("Hello, bee.")
    print("This is Ken.")
    print("Yeah, I remember you. Timberland, size ten and a half. Vibram sole, I believe.")
    print("Why does he talk again?")
    print("Listen, you better go 'cause we're really busy working.")
    print("But it's our yogurt night!")
    print("Bye-bye.")
    print("Why is yogurt night so difficult?!")
    print("You poor thing. You two have been at this for hours!")
    print("Yes, and Adam here has been a huge help.")
    print("Frosting...")
    print("How many sugars?")
    print("Just one. I try not to use the competition.")
    print("So why are you helping me?")
    print("Bees have good qualities. And it takes my mind off the shop. Instead of flowers, people are giving balloon bouquets now.")
    print("Those are great, if you're three.")
    print("And artificial flowers.")
    print("Oh, those just get me psychotic!")
    print("Yeah, me too.")
    print("Bent stingers, pointless pollination.")
    print("Bees must hate those fake things!")
    print("Nothing worse than a daffodil that's had work done.")
    print("Maybe this could make up for it a little bit.")
    print("This lawsuit's a pretty big deal.")
    print("I guess.")
    print("You sure you want to go through with it?")
    print("Am I sure? When I'm done with the humans, they won't be able to say, "+'"Honey, I'+"'m home,"+'" without paying a royalty!')
    print("It's an incredible scene here in downtown Manhattan, where the world anxiously waits, because for the first time in history, we will hear for ourselves if a honeybee can actually speak.")
    print("What have we gotten into here, Barry?")
    print("It's pretty big, isn't it?")
    print("I can't believe how many humans don't work during the day.")
    print("You think billion-dollar multinational food companies have good lawyers?")
    print("Everybody needs to stay behind the barricade.")
    print("What's the matter?")
    print("I don't know, I just got a chill.")
    print("Well, if it isn't the bee team.")
    print("You boys work on this?")
    print("All rise! The Honorable Judge Bumbleton presiding.")
    print("All right. Case number 4475,")
    print("Superior Court of New York,")
    print("Barry Bee Benson v. the Honey Industry is now in session.")
    print("Mr. Montgomery, you're representing the five food companies collectively?")
    print("A privilege.")
    print("Mr. Benson... you're representing all the bees of the world?")
    print("I'm kidding. Yes, Your Honor, we're ready to proceed.")
    print("Mr. Montgomery, your opening statement, please.")
    print("Ladies and gentlemen of the jury, my grandmother was a simple woman. Born on a farm, she believed it was man's divine right to benefit from the bounty of nature God put before us.")
    print("If we lived in the topsy-turvy world Mr. Benson imagines, just think of what would it mean.")
    print("I would have to negotiate with the silkworm for the elastic in my britches!")
    print("Talking bee!")
    print("How do we know this isn't some sort of holographic motion-picture-capture Hollywood wizardry?")
    print("They could be using laser beams! Robotics! Ventriloquism! Cloning! For all we know, he could be on steroids!")
    print("Mr. Benson?")
    print("Ladies and gentlemen, there's no trickery here. I'm just an ordinary bee. Honey's pretty important to me. It's important to all bees. We invented it! We make it. And we protect it with our lives.")
    print("Unfortunately, there are some people in this room who think they can take it from us 'cause we're the little guys!")
    print("I'm hoping that, after this is all over, you'll see how, by taking our honey, you not only take everything we have but everything we are!")
    print("I wish he'd dress like that all the time. So nice!")
    print("Call your first witness.")
    print("So, Mr. Klauss Vanderhayden of Honey Farms, big company you have.")
    print("I suppose so.")
    print("I see you also own Honeyburton and Honron!")
    print("Yes, they provide beekeepers for our farms.")
    print("Beekeeper. I find that to be a very disturbing term.")
    print("I don't imagine you employ any bee-free-ers, do you?")
    print("No.")
    print("I couldn't hear you.")
    print("No.")
    print("No. Because you don't free bees. You keep bees. Not only that, it seems you thought a bear would be an appropriate image for a jar of honey.")
    print("They're very lovable creatures. Yogi Bear, Fozzie Bear, Build-A-Bear.")
    print("You mean like this?")
    print("Bears kill bees!")
    print("How'd you like his head crashing through your living room?! Biting into your couch! Spitting out your throw pillows! OK, that's enough. Take him away.")
    print("So, Mr. Sting, thank you for being here. Your name intrigues me. Where have I heard it before?")
    print("I was with a band called The Police.")
    print("But you've never been a police officer, have you?")
    print("No, I haven't.")
    print("No, you haven't. And so here we have yet another example of bee culture casually stolen by a human for nothing more than a prance-about stage name.")
    print("Oh, please.")
    print("Have you ever been stung, Mr. Sting? Because I'm feeling a little stung, Sting. Or should I say... Mr. Gordon M. Sumner!")
    print("That's not his real name?! You idiots!")
    print("Mr. Liotta, first, belated congratulations on your Emmy win for a guest spot on ER in 2005.")
    print("Thank you. Thank you.")
    print("I see from your resume that you're devilishly handsome with a churning inner turmoil that's ready to blow.")
    print("I enjoy what I do. Is that a crime?")
    print("Not yet it isn't. But is this what it's come to for you? Exploiting tiny, helpless bees so you don't have to rehearse your part and learn your lines, sir?")
    print("Watch it, Benson! I could blow right now!")
    print("This isn't a goodfella.")
    print("This is a badfella!")
    print("Why doesn't someone just step on this creep, and we can all go home?!")
    print("Order in this court!")
    print("You're all thinking it!")
    print("Order! Order, I say!")
    print("Say it!")
    print("Mr. Liotta, please sit down!")
    print("I think it was awfully nice of that bear to pitch in like that. I think the jury's on our side.")
    print("Are we doing everything right, legally?")
    print("I'm a florist.")
    print("Right. Well, here's to a great team.")
    print("To a great team!")
    print("Well, hello.")
    print("Ken!")
    print("Hello.")
    print("I didn't think you were coming.")
    print("No, I was just late I tried to call, but... the battery.")
    print("I didn't want all this to go to waste,")
    print("so I called Barry. Luckily, he was free.")
    print("Oh, that was lucky.")
    print("There's a little left. I could heat it up.")
    print("Yeah, heat it up, sure, whatever.")
    print("So I hear you're quite a tennis player. I'm not much for the game myself. The ball's a little grabby.")
    print("That's where I usually sit. Right... there.")
    print("Ken, Barry was looking at your resume, and he agreed with me that eating with chopsticks isn't really a special skill.")
    print("You think I don't see what you're doing?")
    print("I know how hard it is to find the right job. We have that in common.")
    print("Do we?")
    print("Bees have 100 percent employment, but we do jobs like taking the crud out.")
    print("That's just what I was thinking about doing.")
    print("Ken, I let Barry borrow your razor for his fuzz. I hope that was all right.")
    print("I'm going to drain the old stinger.")
    print("Yeah, you do that.")
    print("Look at that.")
    print("You know, I've just about had it with your little Mind Games.")
    print("What's that?")
    print("Italian Vogue.")
    print("Mamma mia, that's a lot of pages.")
    print("A lot of ads.")
    print("Remember what Van said, why is your life more valuable than mine?")
    print("Funny, I just can't seem to recall that! I think something stinks in here!")
    print("I love the smell of flowers.")
    print("How do you like the smell of flames?!")
    print("Not as much.")
    print("Water bug! Not taking sides!")
    print("Ken, I'm wearing a Chapstick hat!")
    print("This is pathetic!")
    print("I've got issues!")
    print("Well, well, well, a royal flush!")
    print("You're bluffing.")
    print("Am I?")
    print("Surf's up, dude!")
    print("Poo water!")
    print("That bowl is gnarly. Except for those dirty yellow rings!")
    print("Kenneth! What are you doing?!")
    print("You know, I don't even like honey! I don't eat it!")
    print("We need to talk! He's just a little bee!")
    print("And he happens to be the nicest bee I've met in a long time!")
    print("Long time? What are you talking about?! Are there other bugs in your life?")
    print(" No, but there are other things bugging me in life. And you're one of them!")
    print("Fine! Talking bees, no yogurt night...")
    print("My nerves are fried from riding on this emotional roller coaster!")
    print("Goodbye, Ken.")
    print("And for your information, I prefer sugar-free, artificial sweeteners made by man!")
    print("I'm sorry about all that.")
    print("I know it's got an aftertaste! I like it!")
    print("I always felt there was some kind of barrier between Ken and me. I couldn't overcome it.")
    print("Oh, well.")
    print("Are you OK for the trial?")
    print("I believe Mr. Montgomery is about out of ideas.")
    print("We would like to call Mr. Barry Benson Bee to the stand.")
    print("Good idea! You can really see why he's considered one of the best lawyers...")
    print("Yeah.")
    print("Layton, you've gotta weave some magic with this jury, or it's gonna be all over.")
    print("Don't worry. The only thing I have to do to turn this jury around is to remind them of what they don't like about bees.")
    print("You got the tweezers?")
    print("Are you allergic?")
    print("Only to losing, son. Only to losing.")
    print("Mr. Benson Bee, I'll ask you what I think we'd all like to know.")
    print("What exactly is your relationship to that woman?")
    print("We're friends.")
    print("Good friends?")
    print("Yes.")
    print("How good? Do you live together?")
    print("Wait a minute... Are you her little... bedbug?")
    print("I've seen a bee documentary or two. From what I understand, doesn't your queen give birth to all the bee children?")
    print("Yeah, but...")
    print("So those aren't your real parents!")
    print("Oh, Barry...")
    print("Yes, they are!")
    print("Hold me back!")
    print("You're an illegitimate bee, aren't you, Benson?")
    print("He's denouncing bees!")
    print("Don't y'all date your cousins?")
    print("Objection!")
    print("I'm going to pincushion this guy!")
    print("Adam, don't! It's what he wants!")
    print("Oh, I'm hit!! Oh, lordy, I am hit!")
    print("Order! Order!")
    print("The venom! The venom is coursing through my veins! I have been felled by a winged beast of destruction! You see? You can't treat them like equals! They're striped savages! Stinging's the only thing they know! It's their way!")
    print("Adam, stay with me.")
    print("I can't feel my legs.")
    print("What Angel of Mercy will come forward to suck the poison from my heaving buttocks?")
    print("I will have order in this court. Order! Order, please!")
    print("The case of the honeybees versus the human race took a pointed Turn Against the bees yesterday when one of their legal team stung Layton T. Montgomery.")
    print("Hey, buddy.")
    print("Hey.")
    print("Is there much pain?")
    print("Yeah.")
    print("I... I blew the whole case, didn't I?")
    print("It doesn't matter. What matters is")
    print("you're alive. You could have died.")
    print("I'd be better off dead. Look at me.")
    print("They got it from the cafeteria downstairs, in a tuna sandwich. Look, there's a little celery still on it.")
    print("What was it like to sting someone?")
    print("I can't explain it. It was all... All adrenaline and then...and then ecstasy!")
    print("All right.")
    print("You think it was all a trap?")
    print("Of course. I'm sorry. I flew us right into this.")
    print("What were we thinking? Look at us. We're just a couple of bugs in this world.")
    print("What will the humans do to us if they win?")
    print("I don't know.")
    print("I hear they put the roaches in motels. That doesn't sound so bad.")
    print("Adam, they check in, but they don't check out!")
    print("Oh, my.")
    print("Could you get a nurse to close that window?")
    print("Why?")
    print("The smoke.")
    print("Bees don't smoke.")
    print("Right. Bees don't smoke.")
    print("Bees don't smoke!")
    print("But some bees are smoking.")
    print("That's it! That's our case!")
    print("It is? It's not over?")
    print("Get dressed. I've gotta go somewhere.")
    print("Get back to the court and stall. Stall any way you can.")
    print("And assuming you've done step correctly, you're ready for the tub.")
    print("Mr. Flayman.")
    print("Yes? Yes, Your Honor!")
    print("Where is the rest of your team?")
    print("Well, Your Honor, it's interesting. Bees are trained to fly haphazardly, and as a result, we don't make very good time.")
    print("I actually heard a funny story about...")
    print("Your Honor, haven't these ridiculous bugs taken up enough of this court's valuable time? How much longer will we allow these absurd shenanigans to go on?")
    print("They have presented no compelling evidence to support their charges against my clients, who run legitimate businesses.")
    print("I move for a complete dismissal of this entire case!")
    print("Mr. Flayman, I'm afraid I'm going to have to consider Mr. Montgomery's motion.")
    print("But you can't! We have a terrific case.")
    print("Where is your proof?")
    print("Where is the evidence?")
    print("Show me the smoking gun!")
    print("Hold it, Your Honor!")
    print("You want a smoking gun? Here is your smoking gun.")
    print("What is that?")
    print("It's a bee smoker!")
    print("What, this? This harmless little contraption? This couldn't hurt a fly, let alone a bee.")
    print('Look at what has happened to bees who have never been asked, "Smoking or non?" Is this what nature intended for us? To be forcibly addicted to smoke machines and man-made wooden slat work camps?')
    print("Living out our lives as honey slaves to the white man?")
    print("What are we gonna do?")
    print("He's playing the species card.")
    print("Ladies and gentlemen, please, free these bees!")
    print("Free the bees! Free the bees! Free the bees! Free the bees! Free the bees!")
    print("The court finds in favor of the bees!")
    print("Vanessa, we won!")
    print("I knew you could do it! High-five!")
    print("Sorry.")
    print("I'm OK! You know what this means?")
    print("All the honey will finally belong to the bees.")
    print("Now we won't have to work so hard all the time.")
    print("This is an unholy perversion of the balance of nature, Benson.")
    print("You'll regret this.")
    print("Barry, how much honey is out there?")
    print("All right. One at a time.")
    print("Barry, who are you wearing?")
    print("My sweater is Ralph Lauren, and I have no pants.")
    print("What if Montgomery's right?")
    print("What do you mean?")
    print("We've been living the bee way a long time, 27 million years.")
    print("Congratulations on your victory. What will you demand as a settlement?")
    print("First, we'll demand a complete shutdown of all bee work camps.")
    print("Then we want back the honey that was ours to begin with, every last drop.")
    print("We demand an end to the glorification of the bear as anything more than a filthy, smelly, bad-breath stink machine.")
    print("We're all aware of what they do in the woods.")
    print("Wait for my signal. Take him out.")
    print("He'll have nauseous for a few hours, then he'll be fine.")
    print("And we will no longer tolerate bee-negative nicknames...")
    print("But it's just a prance-about stage name!")
    print("...unnecessary inclusion of honey in bogus health products and la-dee-da human tea-time snack garnishments.")
    print("Can't breathe.")
    print("Bring it in, boys!")
    print("Hold it right there! Good.")
    print("Tap it.")
    print("Mr. Buzzwell, we just passed three cups and there's gallons more coming!")
    print("I think we need to shut down!")
    print("Shut down? We've never shut down.")
    print("Shut down honey production!")
    print("Stop making honey!")
    print("Turn your key, sir!")
    print("What do we do now?")
    print("Cannonball!")
    print("We're shutting honey production!")
    print("Mission abort.")
    print("Aborting pollination and nectar detail.")
    print("Returning to base.")
    print("Adam, you wouldn't believe how much honey was out there.")
    print("Oh, yeah?")
    print("What's going on? Where is everybody?")
    print("Are they out celebrating?")
    print("They're home.")
    print("They don't know what to do. Laying out, sleeping in.")
    print("I heard your Uncle Carl was on his way to San Antonio with a cricket.")
    print("At least we got our honey back.")
    print("Sometimes I think, so what if humans liked our honey? Who wouldn't?")
    print("It's the greatest thing in the world! I was excited to be part of making it.")
    print("This was my new desk. This was my new job. I wanted to do it really well. And now...")
    print("Now I can't.")
    print("I don't understand why they're not happy.")
    print("I thought their lives would be better!")
    print("They're doing nothing. It's amazing.")
    print("Honey really changes people.")
    print("You don't have any idea what's going on, do you?")
    print("What did you want to show me?")
    print("This.")
    print("What happened here?")
    print("That is not the half of it.")
    print("Oh, no. Oh, my.")
    print("They're all wilting.")
    print("Doesn't look very good, does it?")
    print("No.")
    print("And whose fault do you think that is?")
    print("You know, I'm gonna guess bees.")
    print("Bees?")
    print("Specifically, me.")
    print("I didn't think bees not needing to make honey would affect all these things.")
    print("It's not just flowers. Fruits, vegetables, they all need bees.")
    print("That's our whole SAT test right there.")
    print("Take away produce, that affects the entire animal kingdom.")
    print("And then, of course...")
    print("The human species?")
    print("So if there's no more pollination, it could all just go south here, couldn't it?")
    print("I know this is also partly my fault.")
    print("How about a suicide pact?")
    print("How do we do it?")
    print("I'll sting you, you step on me.")
    print("That just kills you twice.")
    print("Right, right.")
    print("Listen, Barry... sorry, but I gotta get going.")
    print("I had to open my mouth and talk.")
    print("Vanessa?")
    print("Vanessa? Why are you leaving?")
    print("Where are you going?")
    print("To the final Tournament of Roses parade in Pasadena.")
    print("They've moved it to this weekend because all the flowers are dying.")
    print("It's the Last Chance I'll ever have to see it.")
    print("Vanessa, I just wanna say I'm sorry.")
    print("I never meant it to turn out like this.")
    print("I know. Me neither.")
    print("Tournament of Roses.")
    print("Roses can't do sports.")
    print("Wait a minute. Roses. Roses?")
    print("Roses!")
    print("Vanessa!")
    print("Roses?!")
    print("Barry?")
    print("Roses are flowers!")
    print("Yes, they are.")
    print("Flowers, bees, pollen!")
    print("I know.")
    print("That's why this is the last parade.")
    print("Maybe not.")
    print("Could you ask him to slow down?")
    print("Could you slow down?")
    print("Barry!")
    print("OK, I made a huge mistake.")
    print("This is a total disaster, all my fault.")
    print("Yes, it kind of is.")
    print("I've ruined the planet. I wanted to help you with the flower shop. I've made it worse.")
    print("Actually, it's completely closed down.")
    print("I thought maybe you were remodeling.")
    print("But I have another idea, and it's greater than my previous ideas combined.")
    print("I don't want to hear it!")
    print("All right, they have the roses, the roses have the pollen.")
    print("I know every bee, plant and flower bud in this park.")
    print("All we gotta do is get what they've got back here with what we've got.")
    print("Bees.")
    print("Park.")
    print("Pollen!")
    print("Flowers.")
    print("Repollination!")
    print("Across the nation!")
    print("Tournament of Roses, Pasadena, California.")
    print("They've got nothing but flowers, floats and cotton candy.")
    print("Security will be tight.")
    print("I have an idea.")
    print("Vanessa Bloome, FTD.")
    print("Official floral business. It's real.")
    print("Sorry, ma'am. Nice brooch.")
    print("Thank you. It was a gift.")
    print("Once inside, we just pick the right float.")
    print("How about The Princess and the Pea?")
    print("I could be the princess, and you could be the pea!")
    print("Yes, I got it.")
    print("Where should I sit?")
    print("What are you?")
    print("I believe I'm the pea.")
    print("The pea?")
    print("It goes under the mattresses.")
    print("Not in this fairy tale, sweetheart.")
    print("I'm getting the marshal.")
    print("You do that! This whole parade is a fiasco!")
    print("Let's see what this baby'll do.")
    print("Hey, what are you doing?!")
    print("Then all we do is blend in with traffic... without arousing suspicion.")
    print("Once at the airport, there's no stopping us.")
    print("Stop! Security.")
    print("You and your insect pack your float?")
    print("Yes.")
    print("Has it been in your possession the entire time?")
    print("Would you remove your shoes?")
    print("Remove your stinger.")
    print("It's part of me.")
    print("I know. Just having some fun.")
    print("Enjoy your flight.")
    print("Then if we're lucky, we'll have just enough pollen to do the job.")
    print("Can you believe how lucky we are? We have just enough pollen to do the job!")
    print("I think this is gonna work.")
    print("It's got to work.")
    print("Attention, passengers, this is Captain Scott. We have a bit of bad weather in New York. It looks like we'll experience a couple hours delay.")
    print("Barry, these are cut flowers with no water. They'll never make it.")
    print("I gotta get up there and talk to them.")
    print("Be careful.")
    print("Can I get help with the Sky Mall magazine? I'd like to order the talking inflatable nose and ear hair trimmer.")
    print("Captain, I'm in a real situation.")
    print("What'd you say, Hal?")
    print("Nothing.")
    print("Bee!")
    print("Don't freak out! My entire species...")
    print("What are you doing?")
    print("Wait a minute! I'm an attorney!")
    print("Who's an attorney?")
    print("Don't move.")
    print("Oh, Barry.")
    print("Good afternoon, passengers. This is your captain. Would a Miss Vanessa Bloome in 24B please report to the cockpit? And please hurry!")
    print("What happened here?")
    print("There was a DustBuster, a toupee, a life raft exploded.")
    print("One's bald, one's in a boat, they're both unconscious!")
    print("Is that another bee joke?")
    print("No!")
    print("No one's flying the plane!")
    print("This is JFK control tower, Flight 356. What's your status?")
    print("This is Vanessa Bloome. I'm a florist from New York.")
    print("Where's the pilot?")
    print("He's unconscious, and so is the copilot.")
    print("Not good. Does anyone onboard have flight experience?")
    print("As a matter of fact, there is.")
    print("Who's that?")
    print("Barry Benson.")
    print("From the honey trial?! Oh, great.")
    print("Vanessa, this is nothing more than a big metal bee.")
    print("It's got giant wings, huge engines.")
    print("I can't fly a plane.")
    print("Why not? Isn't John Travolta a pilot?")
    print("Yes.")
    print("How hard could it be?")
    print("Wait, Barry!")
    print("We're headed into some lightning.")
    print("This is Bob Bumble. We have some late-breaking news from JFK Airport, where a suspenseful scene is developing.")
    print("Barry Benson, fresh from his legal victory...")
    print("That's Barry!")
    print("...is attempting to land a plane, loaded with people, flowers and an incapacitated flight crew.")
    print("Flowers?!")
    print("We have a storm in the area and two individuals at the controls with absolutely no flight experience.")
    print("Just a minute. There's a bee on that plane.")
    print("I'm quite familiar with Mr. Benson and his no-account compadres.")
    print("They've done enough damage.")
    print("But isn't he your only hope?")
    print("Technically, a bee shouldn't be able to fly at all.")
    print("Their wings are too small... Haven't we heard this a million times?")
    print('"The surface area of the wings and body mass make no sense."')
    print("Get this on the air!")
    print("Got it.")
    print("Stand by.")
    print("We're going live.")
    print("The way we work may be a mystery to you. Making honey takes a lot of bees doing a lot of small jobs.")
    print("But let me tell you about a small job. If you do it well, it makes a big difference.")
    print("More than we realized. To us, to everyone.")
    print("That's why I want to get bees back to working together. That's the bee way! We're not made of Jell-O.")
    print("We get behind a fellow.")
    print("Black and yellow!")
    print("Hello!")
    print("Left, right, down, hover.")
    print("Hover?")
    print("Forget hover.")
    print("This isn't so hard.")
    print("Beep-beep! Beep-beep!")
    print("Barry, what happened?!")
    print("Wait, I think we were on autopilot the whole time.")
    print("That may have been helping me.")
    print("And now we're not!")
    print("So it turns out I cannot fly a plane.")
    print("All of you, let's get behind this fellow! Move it out!")
    print("Move out!")
    print("Our only chance is if I do what I'd do, you copy me with the wings of the plane!")
    print("Don't have to yell.")
    print("I'm not yelling! We're in a lot of trouble.")
    print("It's very hard to concentrate with that panicky tone in your voice!")
    print("It's not a tone. I'm panicking!")
    print("I can't do this!")
    print("Vanessa, pull yourself together. You have to snap out of it!")
    print("You snap out of it.")
    print("You snap out of it.")
    print("You snap out of it!")
    print("You snap out of it!")
    print("You snap out of it!")
    print("You snap out of it!")
    print("You snap out of it!")
    print("You snap out of it!")
    print("Hold it!")
    print("Why? Come on, it's my turn.")
    print("How is the plane flying?")
    print("I don't know.")
    print("Hello?")
    print("Benson, got any flowers for a happy occasion in there?")
    print("The Pollen Jocks!")
    print("They do get behind a fellow.")
    print("Black and yellow.")
    print("Hello.")
    print("All right, let's drop this tin can on the blacktop.")
    print("Where? I can't see anything. Can you?")
    print("No, nothing. It's all cloudy.")
    print("Come on. You got to think bee, Barry.")
    print("Thinking bee.")
    print("Thinking bee.")
    print("Thinking bee!")
    print("Thinking bee! Thinking bee!")
    print("Wait a minute. I think I'm feeling something.")
    print("What?")
    print("I don't know. It's strong, pulling me.")
    print("Like a 27-million-year-old instinct.")
    print("Bring the nose down.")
    print("Thinking bee!")
    print("Thinking bee! Thinking bee!")
    print("What in the world is on the tarmac?")
    print("Get some lights on that!")
    print("Thinking bee!")
    print("Thinking bee! Thinking bee!")
    print("Vanessa, aim for the flower.")
    print("OK.")
    print("Cut the engines. We're going in on bee power. Ready, boys?")
    print("Affirmative!")
    print("Good. Good. Easy, now. That's it.")
    print("Land on that flower!")
    print("Ready? Full reverse!")
    print("Spin it around!")
    print("Not that flower! The other one!")
    print("Which one?")
    print("That flower.")
    print("I'm aiming at the flower!")
    print("That's a fat guy in a flowered shirt.")
    print("I mean the giant pulsating flower made of millions of bees!")
    print("Pull forward. Nose down. Tail up.")
    print("Rotate around it.")
    print("This is insane, Barry!")
    print("This's the only way I know how to fly.")
    print("Am I koo-koo-kachoo, or is this plane flying in an insect-like pattern?")
    print("Get your nose in there. Don't be afraid. Smell it. Full reverse!")
    print("Just drop it. Be a part of it.")
    print("Aim for the center!")
    print("Now drop it in! Drop it in, woman!")
    print("Come on, already.")
    print("Barry, we did it! You taught me how to fly!")
    print("Yes. No high-five!")
    print("Right.")
    print("Barry, it worked!")
    print("Did you see the giant flower?")
    print("What giant flower? Where? Of course")
    print("I saw the flower! That was genius!")
    print("Thank you.")
    print("But we're not done yet.")
    print("Listen, everyone!")
    print("This runway is covered with the last pollen from the last flowers available anywhere on Earth.")
    print("That means this is our Last Chance. We're the only ones who make honey, pollinate flowers and dress like this.")
    print("If we're gonna survive as a species, this is our moment! What do you say?")
    print("Are we going to be bees, or just Museum of Natural History keychains?")
    print("We're bees!")
    print("Keychain!")
    print("Then follow me! Except Keychain.")
    print("Hold on, Barry. Here. You've earned this.")
    print("Yeah!")
    print("I'm a Pollen Jock! And it's a perfect fit. All I gotta do are the sleeves.")
    print("Oh, yeah.")
    print("That's our Barry.")
    print("Mom! The bees are back!")
    print("If anybody needs to make a call, now's the time. I got a feeling we'll be working late tonight!")
    print("Here's your change. Have a great afternoon! Can I help who's next?")
    print("Would you like some honey with that?")
    print("It is bee-approved. Don't forget these.")
    print("Milk, cream, cheese, it's all me.  And I don't see a nickel!")
    print("Sometimes I just feel like a piece of meat!")
    print("I had no idea.")
    print("Barry, I'm sorry.")
    print("Have you got a moment?")
    print("Would you excuse me?")
    print("My mosquito associate will help you.")
    print("Sorry I'm late.")
    print("He's a lawyer too?")
    print("I was already a blood-sucking parasite. All I needed was a briefcase.")
    print("Have a great afternoon!")
    print("Barry, I just got this huge tulip order, and I can't get them anywhere.")
    print("No problem, Vannie. Just leave it to me.")
    print("You're a lifesaver, Barry. Can I help who's next?")
    print("All right, scramble, jocks! It's time to fly.")
    print("Thank you, Barry!")
    print("That bee is living my life!")
    print("Let it go, Kenny.")
    print("When will this nightmare end?!")
    print("Let it all go.")
    print("Beautiful day to fly.")
    print("Sure is.")
    print("Between you and me,")
    print("I was dying to get out of that office.")
    print("You have got to start thinking bee, my friend.")
    print("Thinking bee!")
    print("Me?")
    print("Hold it. Let's just stop for a second. Hold it.")
    print("I'm sorry. I'm sorry, everyone. Can we stop here?")
    print("I'm not making a major life decision during a production number!")
    print("All right. Take ten, everybody. Wrap it up, guys.")
    print("I had virtually no rehearsal for that.")

if __name__ == "__main__":
    main()